{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "fe233adc-774c-4a7a-9643-2868e5f1f5ce",
   "metadata": {},
   "source": [
    "# ⚡Fluorescence spectroscopy analysis⚡\n",
    "\n",
    "## 💡Main functions\n",
    "\n",
    "### 📈 Function to plot a specific excited wavelength on a graph\n",
    "\n",
    "This function plots fluorescence data on a standard graph and/or an interactive graph, depending on the users choices.\n",
    "\n",
    "plot_fluorescence_graph():\n",
    "\n",
    "This function prompts the user to provide the file location, the sheet name on Excel, the names of the excitation and emission wavelength columns in an Excel file, and the excitation wavelength of interest in nanometers (nm) to label the curve on the graph. It then plots the fluorescence data on a standard graph and/or an interactive graph using Plotly.\n",
    "\n",
    "### 📈 Function to plot several excited wavelength on a graph\n",
    "\n",
    "This function plots a superposition of several excited wavelenghts on a standard graph and, if wanted, an interactive graph.\n",
    "\n",
    "plot_superimposed_graphs():\n",
    "\n",
    "This function prompts the user to input the number of graphs they want to superimpose. It then collects data for each graph, including file location, sheet name on Excel, column names for excitation and emission wavelengths, and the excited wavelengths of interest to label the graph. It plots a static graph and, if wanted, an interactive graph showing the superimposed curves.\n",
    "\n",
    "\n",
    "## 💡Side functions\n",
    "\n",
    "\n",
    "### ↔️ Conversion coma to point (step)\n",
    "\n",
    "The function converts the coma to a point if the step is given with a coma.\n",
    "\n",
    "conversion_coma_point(step)\n",
    "\n",
    "The argument of the function is the step of the spectroscopy machine (given by the user). The given step will be analysed and converted if necessary.\n",
    "\n",
    "### 📝 List of the excited wavelengths considering the step of the spectroscopy machine\n",
    "\n",
    "The function returns a list of the excited wavelengths depending on the step and its type (float or integer).\n",
    "\n",
    "excited_wavelength_list(first, last, step)\n",
    "\n",
    "The arguments of the functions are the following and are asked beforehand to the user: the first and last excited wavelengths values measure and the step of the spectroscopy machine. This function also takes into consideration the different types of values (only one decimal after the point, converts the float values \".0\" in int) to ensure that the list contains the exact same values than in the excel file.\n",
    "\n",
    "### 💫 Instantiation of the class\n",
    "\n",
    "The main function to create the tkinter window and instantiate the ExcelFileUploaderAndConverter class.\n",
    "\n",
    "def main()\n",
    "\n",
    "This function takes onto consideration the response of the user. It starts the event loop which allows the tkinter application to become interactive, processing user input and updating the GUI in response to events. Once the event loop is started, the program will continue running until the user closes the main window or exits the application. It is the sixth function of the class (ExcelFileUploaderAndConverter).\n",
    "\n",
    "### ▶ Windows to upload the excel file (upload button)\n",
    "\n",
    "Initialize the upload of the excel file by browsing through the user's computer through an window and upload button.\n",
    "\n",
    "__init__(self, root)\n",
    "\n",
    "The arguments of the function are defined as follows:\n",
    "\n",
    "    self: A reference to the current instance of the class.\n",
    "    root: An instance of the tkinter.Tk class representing the root tkinter window.\n",
    "\n",
    "It is important to note that this function is the first one of the follwing class:\n",
    "\n",
    "class ExcelFileUploaderAndConverter\n",
    "\n",
    "### 💯 Excel upload and dataframe conversion\n",
    "\n",
    "This function handles the file upload process triggered by the 'Upload' button click created by the above function and converts the content into dataframe.\n",
    "\n",
    "_handle_upload(self)\n",
    "\n",
    "The argument of the function is self which is a reference to the current instance of the class (ExcelFileUploaderAndConverter). The function also displays several message changing depending on the possible events of the uploading process. It is important to note that this function is the second of the class (ExcelFileUploaderAndConverter).\n",
    "\n",
    " 🔭 Content display\n",
    "\n",
    "The function displays the dataframe (converted from the uploaded excel file).\n",
    "\n",
    "_process_excel_file(self)\n",
    "\n",
    "The argument of the function is self which is a reference to the current instance of the class (ExcelFileUploaderAndConverter). It is the third function of the class (ExcelFileUploaderAndConverter). Returns the dataframe.\n",
    "\n",
    "✅ Successful upload\n",
    "\n",
    "The function prints \"successful upload\" if the upload was well processed.\n",
    "\n",
    "_display_success_message(self)\n",
    "\n",
    "The argument of the function is self which is a reference to the current instance of the class (ExcelFileUploaderAndConverter). It is the fourth function of the class (ExcelFileUploaderAndConverter). Returns the successful upload message.\n",
    "\n",
    "❌ Unsuccessful upload\n",
    "\n",
    "The function prints \"unsuccessful upload\" if the upload was not well processed.\n",
    "\n",
    "_display_error_message(self)\n",
    "\n",
    "The argument of the function is self which is a reference to the current instance of the class (ExcelFileUploaderAndConverter). It is the fifth function of the class (ExcelFileUploaderAndConverter). Returns the unsuccessful upload message.\n",
    "function's name\n",
    "\n",
    "The function in one sentence\n",
    "\n",
    "copy paste\n",
    "\n",
    "Details\n",
    "function's name\n",
    "\n",
    "The function in one sentence\n",
    "\n",
    "copy paste\n",
    "\n",
    "Details\n",
    "function's name\n",
    "\n",
    "The function in one sentence\n",
    "\n",
    "copy paste\n",
    "\n",
    "Details\n",
    "function's name\n",
    "\n",
    "The function in one sentence\n",
    "\n",
    "copy paste\n",
    "\n",
    "Details"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "78d5055c-9adf-4fb4-b703-558c1355f9da",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
